"""Added relatirelationship between the tables product, category and supplier

Revision ID: 35c6479d3ad7
Revises: 228840dc557d
Create Date: 2022-01-11 21:07:44.670055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "35c6479d3ad7"
down_revision = "228840dc557d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("category_id", sa.Integer(), nullable=True))
    op.add_column("products", sa.Column("supplier_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "products", "supplier", ["supplier_id"], ["id"])
    op.create_foreign_key(None, "products", "category", ["category_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "products", type_="foreignkey")
    op.drop_constraint(None, "products", type_="foreignkey")
    op.drop_column("products", "supplier_id")
    op.drop_column("products", "category_id")
    # ### end Alembic commands ###
