"""Adjusting table coupon v2

Revision ID: 8dbe5d32e361
Revises: c0b1d5dd21f7
Create Date: 2022-01-11 13:42:38.836591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dbe5d32e361'
down_revision = 'c0b1d5dd21f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
