"""Adjusting table coupon

Revision ID: c0b1d5dd21f7
Revises: 6a95217e3ca9
Create Date: 2022-01-11 13:08:15.427929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c0b1d5dd21f7"
down_revision = "6a95217e3ca9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
